### ISSUE TITLE
Expose BUILD_TEAM_NAME value

### ISSUE THREAD

**Issue by talset** [SWCE/metadata-resource#1]
I have a usecase that require to get the TEAM_NAME in one of my task. I wanted to use the metadata-resource but it seems that BUILD_TEAM_NAME it not handled (https://github.com/SWCE/metadata-resource/blob/master/in/main.go#L37-L41)

It is for a specific reason ? If not, WDYT to add it ?

**Comment by regevbr** [comment]
@ezraroi can you please check if this Metadata can be exposed?

**Comment by ezraroi** [comment]
will check

**Comment by ezraroi** [comment]
https://concourse-ci.org/implementing-resources.html#resource-metadata

**Comment by ezraroi** [comment]
will add $BUILD_TEAM_NAME this

**Comment by regevbr** [comment]
@talset v0.0.3 is relaesd enjoy!
Thanks @ezraroi for the fix

**Comment by ezraroi** [comment]
Working great in our pipelines
